#:kivy 1.5.0

<FingerTouch>:
    size: 150, 150
    canvas:
        Color:
            rgb: self.color
        Ellipse:
            pos: self.pos
            size: self.size

<CLabel>:
    canvas.before:
        Color:
            rgb: self.bgcolor
        Rectangle:
            size: self.size
            pos: self.pos

<SerpentUI>:
    serpent: serpent_area
    finger: finger_touch
    connection_status: connection_status

    FingerTouch:
        id: finger_touch
        opacity: 0.0
        size_hint: None,None

    BoxLayout:
        orientation: 'vertical'
        padding: 20

        #Label:
        #    on_touch_down: root.do_touch(args[1])
        #    text: 'Serpent'
        #    id: serpent_area

        BoxLayout:
            orientation: 'horizontal'
            on_touch_down: root.do_touch(args[1])
            id: serpent_area
            padding: 2

            Label:
                text: 'Head'

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: ''

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

            Label:
                text: 'Tail'

                canvas:
                    Color:
                        rgba: 0.4, 0.4, 0.7, 0.5
                    Rectangle:
                        size: [p-4 for p in self.size]
                        pos: [p+2 for p in self.pos]

        BoxLayout:
            orientation: 'horizontal'
            padding: 10

            CLabel:
                id: connection_status
                text: 'Disconnected'

            Slider:
                canvas:
                    Color:
                        rgba: 1.0,0.0,0.0,0.4
                    Rectangle:
                        pos: self.pos
                        size: self.size
                value: 108
                max: 255
                orientation: 'vertical'
                step: 1
                on_value: root.set_red(args[1])

            Slider:
                canvas:
                    Color:
                        rgba: 0.0,1.0,0.0,0.4
                    Rectangle:
                        pos: self.pos
                        size: self.size
                value: 80
                max: 255
                orientation: 'vertical'
                step: 1
                on_value: root.set_green(args[1])

            Slider:
                canvas:
                    Color:
                        rgba: 0.0,0.0,1.0,0.4
                    Rectangle:
                        pos: self.pos
                        size: self.size
                value: 255
                max: 255
                orientation: 'vertical'
                step: 1
                on_value: root.set_blue(args[1])

            Slider:
                canvas.before:
                    Color:
                        rgb: 0.3,0.2,0.1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                value: 1
                max: 3
                min: 0.2
                step: 0.2
                orientation: 'vertical'
                on_value: root.set_speed(args[1])

            Slider:
                canvas.before:
                    Color:
                        rgb: 0.1,0.2,0.3
                    Rectangle:
                        pos: self.pos
                        size: self.size
                value: 0.98
                max: 0.99
                min: 0.80
                step: 0.01
                orientation: 'vertical'
                on_value: root.set_fade(args[1])

            #Button:
            #    text: 'Stop'
            #    on_press: root.do_stop()

