#:kivy 1.5.0

<SerpentUI>:
    serpent: serpent_area

    BoxLayout:
        orientation: 'vertical'
        padding: 20

        Label:
            on_touch_down: root.do_touch(args[1])
            text: 'Serpent'
            id: serpent_area

        BoxLayout:
            orientation: 'horizontal'
            padding: 10

            Button:
                text: 'Connect Toggle'
                on_press: root.do_press()

            Button:
                text: 'Stop'
                on_press: root.do_stop()
